package store

import (
	"context"
	"database/sql"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/1day0fmylife/Guardian/internal/domain"
	"github.com/1day0fmylife/Guardian/internal/security"
)

func normalizeDeviceCredentialHash(value string) (string, error) {
	value = strings.TrimSpace(value)
	if len(value) != 64 {
		return "", invalidf("device credential hash must be a SHA-256 hex digest")
	}
	decoded, err := hex.DecodeString(value)
	if err != nil || len(decoded) != 32 {
		return "", invalidf("device credential hash must be a SHA-256 hex digest")
	}
	return strings.ToLower(value), nil
}

func validateDeviceCredentialHash(value string) error {
	_, err := normalizeDeviceCredentialHash(value)
	return err
}

// issueDeviceCredentialHashTx registers a credential secret generated by the
// managed device itself. Guardian receives and stores only the SHA-256 hash,
// which lets the device persist the plaintext credential before consuming its
// one-time enrollment token.
func (s *Store) issueDeviceCredentialHashTx(ctx context.Context, tx *sql.Tx, deviceID, tokenHash string) (domain.DeviceCredentialIssued, error) {
	normalizedHash, err := normalizeDeviceCredentialHash(tokenHash)
	if err != nil {
		return domain.DeviceCredentialIssued{}, err
	}
	tokenHash = normalizedHash

	var exists int
	if err := tx.QueryRowContext(ctx, s.q("SELECT COUNT(*) FROM device_credentials WHERE token_hash = ?"), tokenHash).Scan(&exists); err != nil {
		return domain.DeviceCredentialIssued{}, fmt.Errorf("check device credential hash: %w", err)
	}
	if exists != 0 {
		return domain.DeviceCredentialIssued{}, ErrConflict
	}

	id, err := security.NewID()
	if err != nil {
		return domain.DeviceCredentialIssued{}, err
	}
	now := nowText()
	credential := domain.DeviceCredential{ID: id, DeviceID: deviceID, CreatedAt: now}
	if _, err := tx.ExecContext(ctx, s.q(`
		INSERT INTO device_credentials(id, device_id, token_hash, created_at)
		VALUES(?, ?, ?, ?)
	`), id, deviceID, tokenHash, now); err != nil {
		return domain.DeviceCredentialIssued{}, fmt.Errorf("register device credential hash: %w", err)
	}
	return domain.DeviceCredentialIssued{Credential: credential}, nil
}
